const HE_HIM = 'He/Him';
const HE_THEY = 'He/They';
const SHE_HER = 'She/Her';
const SHE_THEY = 'She/They';
const THEY_THEM = 'They/Them';

const pronouns = {
  Riekelt: null,
  PuzzlePea: SHE_HER,
  'Big Jon': null,
  TheBlacktastic: HE_HIM,
  bichphuongballz: HE_HIM,
  Brooke: SHE_HER,
  MASH: THEY_THEM,
  Fell: null,
  angrylanks: HE_HIM,
  cameronvengenz: HE_HIM,
  TheBoyks: HE_HIM,
  PoleCats: null,
  tridenttail: HE_HIM,
  Snowfats: null,
  kirbymastah: HE_HIM,
  WinnerBit: SHE_THEY,
  Shime: HE_HIM,
  'Ryan Ford': HE_HIM,
  SuperBen1755: HE_HIM,
  'Buffet Time': HE_HIM,
  grample: HE_HIM,
  Bluekandy: HE_HIM,
  Celabeat: HE_HIM,
  yelsraek: HE_HIM,
  Aleck47: HE_HIM,
  LookinToad: HE_HIM,
  MrCab55: HE_HIM,
  Tiki: HE_HIM,
  zewing: null,
  BashPrime: HE_HIM,
  zallard1: HE_HIM,
  rossu123: HE_HIM,
  NynahNina: SHE_HER,
  LaurieDBunnykins: SHE_HER,
  Emmoji: SHE_HER,
  Kyoslilmonster: HE_HIM,
  Konasumi: HE_HIM,
  Sickynar: HE_HIM,
  Shenanagans_: HE_HIM,
  AmoebaUK: HE_HIM,
  Tayman: null,
  CardsOfTheHeart: HE_HIM,
  Pea_txt: HE_THEY,
  WhiteHat94: HE_HIM,
  teddy: null,
  cleverpidgeon: HE_HIM,
  'Captain Ezekiel': HE_HIM,
  BahamutX_: HE_HIM,
  MitoRequiem: HE_HIM,
  // ufotekkie: ,
  // seckswrecks: ,
  // giygasblues: ,
  // JoeyBaby69: ,
  // Drakodan: ,
  // 'flying fox': ,
  // Allegro: ,
  // Focus: ,
  // LattMackey: ,
  // Jaxler: ,
  // SilverSonic: ,
  // Siver: ,
  // zeldacubed: ,
  // RDVvsTheWorld: ,
  // gamestabled: ,
  // SuperSonic: ,
  // TapatioJ: ,
  // TheHaxor: ,
  // Retroverse: ,
  // 'dad infinitum': ,
  // Dangers: ,
  // kekumanshoyu: ,
  // Helix: ,
  // electronicLogic: ,
  // NecroSky90: ,
  // TGH: ,
  // gymnast86: ,
  // Azorae: ,
  // RealmCopier: ,
  // mooglemod: ,
  // yoshipro: ,
  // lemonademilk: ,
  // yib: ,
  // Nase: ,
  // rezephos: ,
  // DrunkWario: ,
  // Ecdycis: ,
  // LRock617: ,
  // xWinG: ,
  // Dyson: ,
  // WhitePaaws: ,
  // Murcaz: ,
  // DepCow: ,
  // MrBuchu: ,
  // Tony: ,
  // Mildew: ,
  // Ulvind: ,
  // juh0: ,
  // anthole: ,
  // Nes_: ,
  // Apollo22237: ,
  // Rox: ,
};

function getPronounsForPlayer(playerName) {
  return pronouns[playerName];
}
